{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-api-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  production.json: |-
{{ .Files.Get "config/production.json" | nindent 4 }}
{{- end }}
