import express from 'express';
import statisticsRouter from './statistics';
import identityRouter from './identity';
import repositoryRouter from './repository';
import secretRouter from './secret';
import inventoryRouter from './inventory';
import pluginRouter from './plugin';
import monitoringRouter from './monitoring';
import configRouter from './config';
import reportRouter from './report';
import powerSchedulerRouter from './power-scheduler';
import spotAutomationRouter from './spot-automation';
import billingRouter from './billing';
import addOnsRouter from './add-ons';

const router = express.Router();
router.use('/statistics', statisticsRouter);
router.use('/identity', identityRouter);
router.use('/repository', repositoryRouter);
router.use('/secret', secretRouter);
router.use('/inventory', inventoryRouter);
router.use('/plugin', pluginRouter);
router.use('/monitoring', monitoringRouter);
router.use('/config', configRouter);
router.use('/report', reportRouter);
router.use('/power-scheduler', powerSchedulerRouter);
router.use('/spot-automation', spotAutomationRouter);
router.use('/billing', billingRouter);
router.use('/add-ons', addOnsRouter);
export default router;
